In [1]:
%matplotlib inline
from IPython.display import Image
from numpy import pi
import numpy as np
from qutip import *
from qutip.qip.operations import *
from qutip.qip.circuit import QubitCircuit, Gate
import math
from math import sin, cos

In [2]:
import sys
sys.path.append('..')
sys.path.append('../library')
from library.my_quantum_tool import *
from library.my_gate import ccphase, pauli_x

In [3]:
rho = qutip.ket2dm(qutip.ket("00"))
sigma = rho + qutip.ket2dm(qutip.ket("01"))
sigma = sigma.unit()

In [4]:
# entropy_mutual(rho, selA, selB, base=2.718281828459045, sparse=False)

NameError: name 'selA' is not defined

In [7]:
entropy_mutual?

In [32]:
rho = qutip.ket2dm(qutip.ket("10"))  # 这个表示的是3, 001代表的是1, 及电路最上面那个是1
entropy_mutual(rho, [0], [1])

0.0

In [33]:
sigma = rho + qutip.ket2dm(qutip.ket("01"))
sigma = sigma.unit()  #归一化
sigma

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0. ]]

In [34]:
entropy_mutual(sigma, [0], [1])

0.6931471805599453

In [35]:
state1 = qutip.ket("01")
state1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [44]:
state2 = dot(rz(pi/3, 2, 1), state1)
state2

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.       +0.j ]
 [0.8660254+0.5j]
 [0.       +0.j ]
 [0.       +0.j ]]

In [47]:
density(state2)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

NameError: name 'had' is not defined