# 开始记录一些跟可视化相关的东西

## 比特状态

In [1]:
%matplotlib inline
from IPython.display import Image
from numpy import pi
import numpy as np
from qutip import *
from qutip.qip.operations import *
from qutip.qip.circuit import QubitCircuit, Gate
import math
from math import sin, cos

In [2]:
import sys
sys.path.append('..')
from library.my_quantum_tool import *

In [3]:
rz(pi/3)   #phase 门

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.8660254-0.5j 0.       +0.j ]
 [0.       +0.j  0.8660254+0.5j]]

[<br/>
 ["cos(phi / 2) - i * sin(phi / 2)",0],<br/>
 [0,"cos(phi / 2) + i * sin(phi / 2)"]<br/>
]<br/>
可以看出是0态-30度，1态30度

In [4]:
getExp(0.866-0.5j) #是反着的

(1.0, -30.0)

In [5]:
state = dot(rz(pi/3), snot(),basis(2**1, 0))
state

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.61237244-0.35355339j]
 [0.61237244+0.35355339j]]

In [6]:
getExpState(state)

[[(0.71, -30.0)], [(0.71, 30.0)]]

In [7]:
state = dot(tensor(rz(pi/3), qeye(2)), tensor(snot(), snot()),basis(2**2, 0))
state

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.4330127-0.25j]
 [0.4330127-0.25j]
 [0.4330127+0.25j]
 [0.4330127+0.25j]]

In [8]:
getExpState(state)

[[(0.5, -30.0)], [(0.5, -30.0)], [(0.5, 30.0)], [(0.5, 30.0)]]

In [9]:
tensor(rz(pi/2), qeye(2))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.70710678-0.70710678j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.70710678-0.70710678j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.70710678+0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.70710678+0.70710678j]]

In [10]:
m = rz(pi/3)
m

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.8660254-0.5j 0.       +0.j ]
 [0.       +0.j  0.8660254+0.5j]]

复数相乘表现为幅角相加，模长相乘 https://baike.baidu.com/item/%E5%A4%8D%E6%95%B0%E8%BF%90%E7%AE%97%E6%B3%95%E5%88%99/2568041?fr=aladdin

In [11]:
paresGateMatrix(m)

0	1	
1.0|-30	0	0
0	1.0|30	1


In [12]:
paresStateVec(state)

00 	 (0.5, -30.0)
01 	 (0.5, -30.0)
10 	 (0.5, 30.0)
11 	 (0.5, 30.0)


In [13]:
cphase(pi/2)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]

In [14]:
paresGateMatrix(cphase(pi/2)) #cphase 只有全为1的时候才会转

00	01	10	11	
1.0|0	0	0	0	00
0	1.0|0	0	0	01
0	0	1.0|0	0	10
0	0	0	1.0|90	11


In [15]:
had_state2 = dot(tensor(snot(), snot()), basis(2**2, 0))
paresStateVec(had_state2)

00 	 (0.5, 0.0)
01 	 (0.5, 0.0)
10 	 (0.5, 0.0)
11 	 (0.5, 0.0)


In [16]:
paresStateVec(dot(cphase(pi/2), had_state2))

00 	 (0.5, 0.0)
01 	 (0.5, 0.0)
10 	 (0.5, 0.0)
11 	 (0.5, 90.0)


In [19]:
cnot()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [20]:
paresStateVec(dot(cnot(), had_state2))

00 	 (0.5, 0.0)
01 	 (0.5, 0.0)
10 	 (0.5, 0.0)
11 	 (0.5, 0.0)
